title = 'arrpc'
description = 'Simple, speedy and light Python3 RPC'
url = 'https://github.com/adrianchifor/arrpc'
version = '0.4.1'
author = 'Adrian Chifor'
author_email = 'me@adrianchifor.com'
license = 'Apache License 2.0'
